### PR TITLE
try other methods of extracting subtitles when standard fails

### PR DESCRIPTION
**Pull request by gacopl**
in very rare cases when subtitle in zip file has name consisting of ';' (yes somebody actually does that sic!) standard XBMCExtract fails so i made mod where you can try in this cases to extract using standard utils like 7z unzip and unrar. Example of such sub is here (first sub): http://napisy24.pl/search.php?str=vampire+diaries+3x22

### CODE REVIEW

**Comment by amet** [comment]
I am sorry but I will not pull this :(

if there is an error with xbmc.extract() then we better fix that instead of hacking it like this

**Comment by gacopl** [comment]
yeah i thoight so but i had to try:) i will use this for the meantime,
could you pass the problem xbmc-team?

2012/9/6 Zeljko Ametovic notifications@github.com

**Comment by amet** [comment]
hehe, I will ;)

**Comment by gacopl** [comment]
yeah cause you are xbmc-team :)

Anyway i took a closer look into builtins.cpp then went to zipmanager and
it seems they are using their own implementation of unzipping algorithm, so
i dont think they will do something about it before frodo release if they
will do anything with it at all. So i checked some other options and rar
files are not an issue at all the problematic is only ziped so i changed
the code and made use of zipfile python so now actual code is just only 3
lines and looks slicker. Call me stubborn :) but i think it would be wise
to pull it until they will fix the XBMCExtract if they will do it at all.

Btw did you see any site serving subs in rars? because me not, so maybe the
best option would be to ditch XBMCExtract and trust internal python lib to
do the job of unzipping

Sorry for bugging you just got too much excited about my first commit to
community that was actually useful :) now i could move mountains

cheers and of course i sent pull rq,  you'll do what you think is best :)

take care mate

2012/9/6 Zeljko Ametovic notifications@github.com

**Comment by amet** [comment]
its not going to happen... there are RAR files that need extracting, look at the services included

**Comment by amet** [comment]
I can open the zip file that includes ";" just fine on OSX, I cant get that file from the site as it needs login

**Comment by gacopl** [comment]
gacopl:amet21 :)

i can extract the file in system normally only when downloading this
perticular sub from within xbmc it gets extraction error i traced it and it
hangs right after xbmcExtract
And i also had problems through my one year career with xbmc i had at least
10 cases when i could not get the sub and had to pick another because those
specific ones were not able to extract now i know at least why :)

2012/9/7 Zeljko Ametovic notifications@github.com

**Pull request closed without merging**
