### PR TITLE
Added PortugueseBrazilian to LegendasDivx.com service.

### PR DESCRIPTION
**Pull request by highlandr**
After requests the service has now Portuguese Brazilian!

### CODE REVIEW

**Comment by amet** [comment]
Hi, 

can this be squashed into one commit please... just trying to keep it clean

thx for all your contribution

**Comment by highlandr** [comment]
yes if I remember how to use git properly :p
Been a pain with windows 8 ...

**Comment by highlandr** [comment]
should be ok now ... :) I hope!

**Comment by amet** [comment]
something is not right... I cant merge this ... wanna check it out?

**Comment by highlandr** [comment]
I guess the squash didn't work properly!
I'll check it out asap. I'm away from the code atm.

**Comment by amet** [comment]
no issue, i am way too drunk to be reviewing it anyway :)

**Pull request merged**
