### PR TITLE
Added Napisy24.pl; update for addon.xml

### PR DESCRIPTION
**Pull request by mrto**
Hi.
I've added Napisy24.pl service. Both Napisy.me and Napisy24.pl using the same database for subs, but Napisy24.pl provides support for stacked movie files and rating for subtitles.
Greetings,
mrto

### CODE REVIEW

**Comment by amet** [comment]
I am not sure I understand whats happening with these 2 commits...

can you please do a fresh repo pull, apply the changes needed and request it again in one commit

**Comment by mrto** [comment]
How to do "fresh repo pull"? Delete fork, and fork it again? I cannot find it in github help.

**Comment by amet** [comment]
yeah, I think that would be one way of doing it

**Comment by mrto** [comment]
Wow, this gthub system is clever. After delete/forking again/adding changes locally/push to remote, this pull request catch changes. I think it is ok now. Sorry, again, for mess.
Greetings,
mrto

**Comment by amet** [comment]
dont mind me asking, if Napisyme is using Napisy24 DB, why have both of them?

**Comment by mrto** [comment]
Napisy.me site is clean and simple but don't contain any info about rating or cd amount. Napisy24.pl contains much more info but their site is mess. Initially planned to merge this two services:
- primary info from napisy.me + rating, cd info info from napisy24.pl), and but I failed to do so. Maybe in future I be able to sort it out. Meantime I would like to have both of them. 
  But, it is your project, you do what you want.
  Greetings,
  mrto

sorry for my poor english skills (they are poor as much as my python skills) :)

**Pull request merged**
