### PR TITLE
Service LegendasDivx.com version 0.2.1

### PR DESCRIPTION
**Pull request by highlandr**
See service notes for changes.

### CODE REVIEW

**Comment by amet** [comment]
Winblows? nah I dont think so :) I am not a fan on Win, but no reason to make it ugly.

are you planing any more changes? I want to push it to official repo but only if you are done with changes

**Comment by highlandr** [comment]
Want me to change the winblows thing?:) hehe
For now I think I'm done.
The bug of being in the root was annoying, script would return an error (gui too) ;)
Btw how can I pass the name I want to the title when I do a Parent Search? For example when it's a 2CD rls it will show searching 'CD1' or 'CD2' instead I wanted to pass the name of the movie or whatever. In the root if you do a Parent Search it will show nothing (' '). For that last comment the script should detect the root and send a MSG like "Can't do parent search on a root path" :)
Thanks.

**Comment by amet** [comment]
I would love for you to change it, we dont want insulting people just cos they use windows. :)

not sure I understand what you mean with the root issue, give me a working example please

**Comment by highlandr** [comment]
done with the winblows thing.
I msg'ed you on irc about the example.

**Comment by highlandr** [comment]
Hi Amet, when are you going to release these commits? The current one has the path bug which is bad :)
Thanks.

**Comment by amet** [comment]
it will happen, you shouldn't have released it with a bug :p

**Comment by highlandr** [comment]
yeh I know but I usualy don't have files in the root of the drive nor I use the local harddrive :)
I only use Samba, my bad! Can't beat myself more! hehe

**Pull request closed without merging**
