### PR TITLE
[lang] November update of language files

### PR DESCRIPTION
**Pull request by alanwww1**
Update from XBMC main Transifex project:https://www.transifex.com/projects/p/XBMC-Main-Frodo/resource/script-xbmc-subtitles/
All xml files are machine generated from the PO files with my update utility https://github.com/xbmc/translations/tree/master/tool/xbmc-txupdate

Github repo where I regulary update these files: https://github.com/xbmc/translations/tree/master/translations/xbmc-main-frodo/merged-langfiles/addons_ext_plugins/script.xbmc.subtitles

Some strings are auto tranlsted using Transifex translation memory.

Cheers, Attila

### CODE REVIEW

**Comment by amet** [comment]
thanks!!

**Comment by amet** [comment]
@alanwww1 

any way to get my hands on all .po files in language folder as its needed for XBMC? I can then remove all xml and replace with .po for ease of update in the future

**Comment by alanwww1** [comment]
@amet 
Currently I generated XML files instead of POs, because I thought you want to keep compatibility with Eden for a while. If not, I can generate POs in the first place. Also if you need, I can generate both.

I always update the files here, but I can generate PRs for you if you don't have time to make these updates:
https://github.com/xbmc/translations/tree/master/translations/xbmc-main-frodo/merged-langfiles/addons_ext_plugins/script.xbmc.subtitles

Just let me know how you want it. XMLs, POs, or both ?

Thanks,
Attila

**Comment by amet** [comment]
@alanwww1 
I can pull occasionally or before version releases, if you make them POs I will use that as this version of addon is only Frodo

Thanks!
amet

**Comment by alanwww1** [comment]
@amet 
Ok. That's great. I make sure to update it often.
I'll convert them to POs with the next update.

Thanks!
Attila

**Comment by alanwww1** [comment]
@amet 
I updated the files. Converted string files to POs.
Thanks, cheers, Attila

**Comment by amet** [comment]
@alanwww1 where? I dont see them anywhere... :(

**Comment by alanwww1** [comment]
@amet 
Under the link I gave you:
https://github.com/xbmc/translations/tree/master/translations/xbmc-main-frodo/merged-langfiles/addons_ext_plugins/script.xbmc.subtitles

Of course you need the addon.xml file and all the stuff under resources/languages/

BTW, I am writing a small downloader utility which you just run and it downloads all necessary files for you from the github repo and put them in the right places at your local repo. This will make things really easy for all addon developers.

**Pull request merged**
