### PR TITLE
Itasa: year bug fixed

### PR DESCRIPTION
**Pull request by cagnulein**
Sometimes, using sickbeard with xbmc, it downloads shows with year information in the title. 
E.g. Castle (2009)

Itasa hasn't year information in titles.

So, if searching for "Castle (2009)" the scripts find nothing, i added the ability to search for "Castle" automatically.

### CODE REVIEW

**Comment by amet** [comment]
commited, but not sure if you wanted this in eden rather than dharma

**Comment by cagnulein** [comment]
For me is the same :) I would like only to fix a itasa issue. It's up to you choosing version :)

**Comment by amet** [comment]
you only asked for it to go into Dharma.. if you use Eden XBMC you will not get the fix

**Comment by cagnulein** [comment]
How can i ask to fix in Eden? Have you got another repo for it?

**Comment by amet** [comment]
same repo, eden-pre branch 

https://github.com/amet/script.xbmc.subtitles/tree/eden-pre

**Comment by cagnulein** [comment]
sorry, i'm newbie about git stuffs :) Done anyway.

**Pull request merged**
