### PR TITLE
Fixed argenteam service

### PR DESCRIPTION
**Pull request by estemendoza**
Fixed a strange error with debug logs.

### CODE REVIEW

**Comment by amet** [comment]
I cannot merge this, is this done against the latest in github?

**Comment by estemendoza** [comment]
I suppose, but don't rely on me cause I really don't understand git very well yet.

We can do 2 things:

1) Guide me on how to check that
2) View the changes that I made to the file and commit it your self (there are only a few changes)

**Comment by amet** [comment]
you have made changes to and old branch, pull latest 

git rebase and push back to a different branch and request the PR again from it.

I can do it, but you can also learn it :D

**Comment by estemendoza** [comment]
I'm really lost on this.

Let's start over again.

I have my branch,
https://github.com/estemendoza/script.xbmc.subtitleswhere I committed
my changes.

I have deleted cloned repo I had on my machine, because I was doing really
nasty things :P

What should I do now?

Thanks for you patience

On Sun, Mar 25, 2012 at 3:28 PM, Zeljko Ametovic <
reply@reply.github.com

**Pull request closed without merging**
