### PR TITLE
Added support for Subscenter.org

### PR DESCRIPTION
**Pull request by orivar**
Tested for both tv shows and movies, multiple result pages and both .zip and .rar subtitle archives.

### CODE REVIEW

**Comment by amet** [comment]
I have removed sratim service as per your instructions, why is there Version 1.2 in there now?

**Comment by orivar** [comment]
I apologize, like I said on the forum I didn't know how to update my stream before applying the changes and sending a pull request. Only the files under Subscenter are new, everything else is from 2.3.7 when I forked your repo.

I'm sorry for the mix up, next time I will update my repo before commiting any changes. Can you pick out only the new service?

**Comment by amet** [comment]
I can, It would be good if you added the stuff in settings.xml but I can do that
cheers

**Comment by orivar** [comment]
I'm not really sure what changes need to be made - is adding this line:
<setting id="Subscenter" type="bool" label="Subscenter.org" default="false"/>
enough?
Will it add it both to the options screen and the actual plugin gui?

**Comment by amet** [comment]
yes, thats all its needed, I have done it for now. thx for the service. its in my github and will go in soon.

**Pull request closed without merging**
