### PR TITLE
Sratim service now works

### PR DESCRIPTION
**Pull request by BBLN**
Edited script.xbmc.subtitles/resources/lib/services/Sratim/service.py via GitHub

### CODE REVIEW

**Comment by orivar** [comment]
I've just noticed it's broken and fixed it myself (with a shorter patch). Thanks for the submission, I'll be updating using my changes though.

**Comment by BBLN** [comment]
I still can't find subtitles for The Office (US) or Doctor Who (2005), still thinking how to fix that

**Comment by orivar** [comment]
Well, Sratim doesn't support show names with parentheses, so it's really "their fault". You could replace the search string, removing them and everything in them, but keep in mind you'll find results for both the British and the US versions of The Office, etc'.

**Comment by BBLN** [comment]
Closed.
https://github.com/amet/script.xbmc.subtitles/pull/48

**Pull request closed without merging**
