### PR TITLE
Version 0.1.7

### PR DESCRIPTION
**Pull request by highlandr**
# BUG found in multi packs is now fixed.
# Added more accuracy to the selection of subtitle to load. Now checks the release dirname against the subtitles downloaded.
# When no sync is found and if the substitle name is not equal to the release dirname or release filename it will load one random subtitle from the package.

Signed-off-by: HiGhLaNdR highlander@teknorage.com

### CODE REVIEW

**Comment by highlandr** [comment]
It's a major bug on the code, it will not load the multi packs correctly, if you guys can release asap would be nice :)
Thanks.

**Comment by highlandr** [comment]
New features added ;)

**Comment by amet** [comment]
Hi, added it to github, will push in a week or so... I did an update yesterday :(

in future when referring to version please call it "Service LegendasDivx version 0.1.9" rather than just v0.1.9 to avoid confusion

**Comment by highlandr** [comment]
ok.

**Pull request merged**
