### PR TITLE
Sratim 2.0, Subscenter 1.1

### PR DESCRIPTION
**Pull request by orivar**
Sratim fixed - changed RE patterns and links to match new site layout, tv show support fixed.
Subscenter updated - fixed support for non-Hebrew subtitles.

### CODE REVIEW

**Comment by amet** [comment]
hi,

thx for this :)

mind doing a clean one so that I can merge it nicely or telling me which one of this commits I need to pull to my repo :)

cheers mate
amet

**Comment by orivar** [comment]
I'd love to do a clean pull with just the changes but I have to admit I don't really know how... :-/
If you already fixed the missing **init**.py on Subscenter you only need to pick f1ca612, c38d7ab and 43f5db4.

If I could figure out how to remove the commits I don't need I'd gladly remove them instead.

**Comment by amet** [comment]
ok, merged to my repo, let it sit there for a few days and we can push to official then

thx again

PS: see if you can figure out how to do clean pull requests :)

**Comment by orivar** [comment]
Would you mind helping me learn how to do one? Is it just that I'm doing something wrong when issuing the pull request, or is it something else? (in which case I'd love to walk you through the commands I use and see if we can figure out what I'm doing wrong).

**Comment by amet** [comment]
Hi again :)

what you need is to delete the fork now, and fork it again. then every time
you want to work on it you should merge my changes in and then request the
pull when there is only your changes that differ from my fork.

difficult for me to help you on how to do it as I have no idea what OS are
you on, but look for a GUI solution for your OS on Google.

fork my repo
make changes
commit changes
request the pull

later, after my repo has changed

merge my repo with your fork to get the latest code in
make changes
commit changes
request the pull

look around github and google for how-to

cheers
amet

**Pull request closed without merging**
